import { ReflectionsMessage } from "./ReflectionsMessage";

export const ReflectionsMessagesMockData: ReflectionsMessage[] = [
    {
        id: 1,
        content: "Today's conclusion from Doe. Lorem ipsum dolor sit amet",
        isUser: false,
        isCode: true,
        isPinned: false,
        day: "Mon",
        time: "9:41 AM",
        isRead: false,
    },
    {
        id: 2,
        content: "All work and no play make Joe a dull boy",
        isUser: true,
        isCode: false,
        isPinned: true,
        day: "Mon",
        time: "4:32 PM",
        isRead: false,
    },

    {
        id: 3,
        content: "Today's conclusion from Doe. Lorem ipsum dolor sit amet",
        isUser: true,
        isCode: false,
        isPinned: false,
        day: "Tue",
        time: "10:15 AM",
        isRead: false,
    },
    {
        id: 4,
        content: "All work and no play make Joe a dull boy",
        isUser: false,
        isCode: true,
        isPinned: true,
        day: "Tue",
        time: "3:20 PM",
        isRead: false,
    },

    {
        id: 5,
        content: "Today's conclusion from Doe. Lorem ipsum dolor sit amet",
        isUser: false,
        isCode: true,
        isPinned: false,
        day: "Wed",
        time: "8:30 AM",
        isRead: false,
    },
    {
        id: 6,
        content: "All work and no play make Joe a dull boy",
        isUser: true,
        isCode: false,
        isPinned: false,
        day: "Wed",
        time: "5:45 PM",
        isRead: false,
    },

    {
        id: 7,
        content: "Today's conclusion from Doe. Lorem ipsum dolor sit amet",
        isUser: false,
        isCode: true,
        isPinned: true,
        day: "Thu",
        time: "11:00 AM",
        isRead: false,
    },
    {
        id: 8,
        content: "All work and no play make Joe a dull boy",
        isUser: true,
        isCode: false,
        isPinned: false,
        day: "Thu",
        time: "2:30 PM",
        isRead: false,
    },

    {
        id: 9,
        content: "Today's conclusion from Doe. Lorem ipsum dolor sit amet",
        isUser: true,
        isCode: false,
        isPinned: false,
        day: "Fri",
        time: "9:15 AM",
        isRead: false,
    },
    {
        id: 10,
        content: "All work and no play make Joe a dull boy",
        isUser: false,
        isCode: true,
        isPinned: true,
        day: "Fri",
        time: "4:00 PM",
        isRead: false,
    },

    {
        id: 11,
        content: "Today's conclusion from Doe. Lorem ipsum dolor sit amet",
        isUser: false,
        isCode: true,
        isPinned: false,
        day: "Sat",
        time: "10:45 AM",
        isRead: false,
    },
    {
        id: 12,
        content: "All work and no play make Joe a dull boy",
        isUser: true,
        isCode: false,
        isPinned: false,
        day: "Sat",
        time: "6:30 PM",
        isRead: false,
    },

    {
        id: 13,
        content: "Today's conclusion from Doe. Lorem ipsum dolor sit amet",
        isUser: true,
        isCode: false,
        isPinned: true,
        day: "Sun",
        time: "11:20 AM",
        isRead: false,
    },
    {
        id: 14,
        content: "All work and no play make Joe a dull boy",
        isUser: false,
        isCode: true,
        isPinned: false,
        day: "Sun",
        time: "5:00 PM",
        isRead: false,
    },
];
